/**
 * This class is generated by jOOQ
 */
package ge.economy.intranet.database.database.tables.records;


import ge.economy.intranet.database.database.tables.Personal;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonalRecord extends UpdatableRecordImpl<PersonalRecord> implements Record13<Integer, Integer, Integer, Integer, String, String, String, Date, String, String, String, Integer, Integer> {

	private static final long serialVersionUID = -542283207;

	/**
	 * Setter for <code>public.personal.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.personal.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.personal.organisation_id</code>.
	 */
	public void setOrganisationId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.personal.organisation_id</code>.
	 */
	public Integer getOrganisationId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.personal.structure_id</code>.
	 */
	public void setStructureId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.personal.structure_id</code>.
	 */
	public Integer getStructureId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.personal.position_id</code>.
	 */
	public void setPositionId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.personal.position_id</code>.
	 */
	public Integer getPositionId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.personal.first_name</code>.
	 */
	public void setFirstName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.personal.first_name</code>.
	 */
	public String getFirstName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.personal.last_name</code>.
	 */
	public void setLastName(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.personal.last_name</code>.
	 */
	public String getLastName() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.personal.mail</code>.
	 */
	public void setMail(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.personal.mail</code>.
	 */
	public String getMail() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.personal.birth_date</code>.
	 */
	public void setBirthDate(Date value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.personal.birth_date</code>.
	 */
	public Date getBirthDate() {
		return (Date) getValue(7);
	}

	/**
	 * Setter for <code>public.personal.pid_number</code>.
	 */
	public void setPidNumber(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.personal.pid_number</code>.
	 */
	public String getPidNumber() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.personal.phone_number</code>.
	 */
	public void setPhoneNumber(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.personal.phone_number</code>.
	 */
	public String getPhoneNumber() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>public.personal.address</code>.
	 */
	public void setAddress(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.personal.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>public.personal.group_id</code>.
	 */
	public void setGroupId(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.personal.group_id</code>.
	 */
	public Integer getGroupId() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>public.personal.status_id</code>.
	 */
	public void setStatusId(Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>public.personal.status_id</code>.
	 */
	public Integer getStatusId() {
		return (Integer) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Integer, Integer, Integer, Integer, String, String, String, Date, String, String, String, Integer, Integer> fieldsRow() {
		return (Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Integer, Integer, Integer, Integer, String, String, String, Date, String, String, String, Integer, Integer> valuesRow() {
		return (Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Personal.PERSONAL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Personal.PERSONAL.ORGANISATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Personal.PERSONAL.STRUCTURE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Personal.PERSONAL.POSITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Personal.PERSONAL.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Personal.PERSONAL.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Personal.PERSONAL.MAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field8() {
		return Personal.PERSONAL.BIRTH_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Personal.PERSONAL.PID_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Personal.PERSONAL.PHONE_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Personal.PERSONAL.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return Personal.PERSONAL.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field13() {
		return Personal.PERSONAL.STATUS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getOrganisationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getStructureId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getPositionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getMail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value8() {
		return getBirthDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getPidNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getPhoneNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value13() {
		return getStatusId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value2(Integer value) {
		setOrganisationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value3(Integer value) {
		setStructureId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value4(Integer value) {
		setPositionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value5(String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value6(String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value7(String value) {
		setMail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value8(Date value) {
		setBirthDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value9(String value) {
		setPidNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value10(String value) {
		setPhoneNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value11(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value12(Integer value) {
		setGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord value13(Integer value) {
		setStatusId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, Date value8, String value9, String value10, String value11, Integer value12, Integer value13) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PersonalRecord
	 */
	public PersonalRecord() {
		super(Personal.PERSONAL);
	}

	/**
	 * Create a detached, initialised PersonalRecord
	 */
	public PersonalRecord(Integer id, Integer organisationId, Integer structureId, Integer positionId, String firstName, String lastName, String mail, Date birthDate, String pidNumber, String phoneNumber, String address, Integer groupId, Integer statusId) {
		super(Personal.PERSONAL);

		setValue(0, id);
		setValue(1, organisationId);
		setValue(2, structureId);
		setValue(3, positionId);
		setValue(4, firstName);
		setValue(5, lastName);
		setValue(6, mail);
		setValue(7, birthDate);
		setValue(8, pidNumber);
		setValue(9, phoneNumber);
		setValue(10, address);
		setValue(11, groupId);
		setValue(12, statusId);
	}
}
