/**
 * This class is generated by jOOQ
 */
package ge.economy.intranet.database.database.tables.records;


import ge.economy.intranet.database.database.tables.Reservation;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReservationRecord extends UpdatableRecordImpl<ReservationRecord> implements Record8<Integer, Integer, Date, Date, String, String, Integer, Integer> {

	private static final long serialVersionUID = 324304616;

	/**
	 * Setter for <code>public.reservation.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.reservation.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.reservation.hall_id</code>.
	 */
	public void setHallId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.reservation.hall_id</code>.
	 */
	public Integer getHallId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.reservation.start_date</code>.
	 */
	public void setStartDate(Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.reservation.start_date</code>.
	 */
	public Date getStartDate() {
		return (Date) getValue(2);
	}

	/**
	 * Setter for <code>public.reservation.end_date</code>.
	 */
	public void setEndDate(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.reservation.end_date</code>.
	 */
	public Date getEndDate() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>public.reservation.name</code>.
	 */
	public void setName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.reservation.name</code>.
	 */
	public String getName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.reservation.description</code>.
	 */
	public void setDescription(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.reservation.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.reservation.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.reservation.user_id</code>.
	 */
	public Integer getUserId() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>public.reservation.organisation_id</code>.
	 */
	public void setOrganisationId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.reservation.organisation_id</code>.
	 */
	public Integer getOrganisationId() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Date, Date, String, String, Integer, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Date, Date, String, String, Integer, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Reservation.RESERVATION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Reservation.RESERVATION.HALL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field3() {
		return Reservation.RESERVATION.START_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return Reservation.RESERVATION.END_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Reservation.RESERVATION.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Reservation.RESERVATION.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Reservation.RESERVATION.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Reservation.RESERVATION.ORGANISATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getHallId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value3() {
		return getStartDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getEndDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getOrganisationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReservationRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReservationRecord value2(Integer value) {
		setHallId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReservationRecord value3(Date value) {
		setStartDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReservationRecord value4(Date value) {
		setEndDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReservationRecord value5(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReservationRecord value6(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReservationRecord value7(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReservationRecord value8(Integer value) {
		setOrganisationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReservationRecord values(Integer value1, Integer value2, Date value3, Date value4, String value5, String value6, Integer value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ReservationRecord
	 */
	public ReservationRecord() {
		super(Reservation.RESERVATION);
	}

	/**
	 * Create a detached, initialised ReservationRecord
	 */
	public ReservationRecord(Integer id, Integer hallId, Date startDate, Date endDate, String name, String description, Integer userId, Integer organisationId) {
		super(Reservation.RESERVATION);

		setValue(0, id);
		setValue(1, hallId);
		setValue(2, startDate);
		setValue(3, endDate);
		setValue(4, name);
		setValue(5, description);
		setValue(6, userId);
		setValue(7, organisationId);
	}
}
