/**
 * This class is generated by jOOQ
 */
package ge.economy.intranet.database.database.tables.records;


import ge.economy.intranet.database.database.tables.Structure;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StructureRecord extends UpdatableRecordImpl<StructureRecord> implements Record7<Integer, Integer, Integer, String, String, String, Boolean> {

	private static final long serialVersionUID = 1691454582;

	/**
	 * Setter for <code>public.structure.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.structure.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.structure.parent_id</code>.
	 */
	public void setParentId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.structure.parent_id</code>.
	 */
	public Integer getParentId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.structure.organisation_id</code>.
	 */
	public void setOrganisationId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.structure.organisation_id</code>.
	 */
	public Integer getOrganisationId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.structure.name</code>.
	 */
	public void setName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.structure.name</code>.
	 */
	public String getName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.structure.description</code>.
	 */
	public void setDescription(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.structure.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.structure.ldap_key</code>.
	 */
	public void setLdapKey(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.structure.ldap_key</code>.
	 */
	public String getLdapKey() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.structure.visible</code>.
	 */
	public void setVisible(Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.structure.visible</code>.
	 */
	public Boolean getVisible() {
		return (Boolean) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, Integer, String, String, String, Boolean> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, Integer, String, String, String, Boolean> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Structure.STRUCTURE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Structure.STRUCTURE.PARENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Structure.STRUCTURE.ORGANISATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Structure.STRUCTURE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Structure.STRUCTURE.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Structure.STRUCTURE.LDAP_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field7() {
		return Structure.STRUCTURE.VISIBLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getParentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getOrganisationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getLdapKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value7() {
		return getVisible();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord value2(Integer value) {
		setParentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord value3(Integer value) {
		setOrganisationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord value4(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord value5(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord value6(String value) {
		setLdapKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord value7(Boolean value) {
		setVisible(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StructureRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, Boolean value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StructureRecord
	 */
	public StructureRecord() {
		super(Structure.STRUCTURE);
	}

	/**
	 * Create a detached, initialised StructureRecord
	 */
	public StructureRecord(Integer id, Integer parentId, Integer organisationId, String name, String description, String ldapKey, Boolean visible) {
		super(Structure.STRUCTURE);

		setValue(0, id);
		setValue(1, parentId);
		setValue(2, organisationId);
		setValue(3, name);
		setValue(4, description);
		setValue(5, ldapKey);
		setValue(6, visible);
	}
}
