/**
 * This class is generated by jOOQ
 */
package ge.economy.intranet.database.database.tables;


import ge.economy.intranet.database.database.Keys;
import ge.economy.intranet.database.database.Public;
import ge.economy.intranet.database.database.tables.records.HallRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hall extends TableImpl<HallRecord> {

	private static final long serialVersionUID = -980572665;

	/**
	 * The reference instance of <code>public.hall</code>
	 */
	public static final Hall HALL = new Hall();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<HallRecord> getRecordType() {
		return HallRecord.class;
	}

	/**
	 * The column <code>public.hall.id</code>.
	 */
	public final TableField<HallRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.hall.name</code>.
	 */
	public final TableField<HallRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.hall.description</code>.
	 */
	public final TableField<HallRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.hall.organisation_id</code>.
	 */
	public final TableField<HallRecord, Integer> ORGANISATION_ID = createField("organisation_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.hall.is_active</code>.
	 */
	public final TableField<HallRecord, Boolean> IS_ACTIVE = createField("is_active", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>public.hall</code> table reference
	 */
	public Hall() {
		this("hall", null);
	}

	/**
	 * Create an aliased <code>public.hall</code> table reference
	 */
	public Hall(String alias) {
		this(alias, HALL);
	}

	private Hall(String alias, Table<HallRecord> aliased) {
		this(alias, aliased, null);
	}

	private Hall(String alias, Table<HallRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<HallRecord, Integer> getIdentity() {
		return Keys.IDENTITY_HALL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<HallRecord> getPrimaryKey() {
		return Keys.HALL_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<HallRecord>> getKeys() {
		return Arrays.<UniqueKey<HallRecord>>asList(Keys.HALL_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Hall as(String alias) {
		return new Hall(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Hall rename(String name) {
		return new Hall(name, null);
	}
}
