/**
 * This class is generated by jOOQ
 */
package ge.economy.intranet.database.database;


import ge.economy.intranet.database.database.tables.Group;
import ge.economy.intranet.database.database.tables.Hall;
import ge.economy.intranet.database.database.tables.Organisation;
import ge.economy.intranet.database.database.tables.Personal;
import ge.economy.intranet.database.database.tables.Position;
import ge.economy.intranet.database.database.tables.Reservation;
import ge.economy.intranet.database.database.tables.Status;
import ge.economy.intranet.database.database.tables.Structure;
import ge.economy.intranet.database.database.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = -1645516094;

	/**
	 * The reference instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.GROUP_ID_SEQ,
			Sequences.HALL_ID_SEQ,
			Sequences.ORGANISATION_ID_SEQ,
			Sequences.PERSONAL_ID_SEQ,
			Sequences.POSITION_ID_SEQ,
			Sequences.RESERVATION_ID_SEQ,
			Sequences.STATUS_ID_SEQ,
			Sequences.STRUCTURE_ID_SEQ,
			Sequences.USER_ID_SEQ);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Group.GROUP,
			Hall.HALL,
			Organisation.ORGANISATION,
			Personal.PERSONAL,
			Position.POSITION,
			Reservation.RESERVATION,
			Status.STATUS,
			Structure.STRUCTURE,
			User.USER);
	}
}
