/**
 * This class is generated by jOOQ
 */
package ge.economy.intranet.database.database;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.group_id_seq</code>
	 */
	public static final Sequence<Long> GROUP_ID_SEQ = new SequenceImpl<Long>("group_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.hall_id_seq</code>
	 */
	public static final Sequence<Long> HALL_ID_SEQ = new SequenceImpl<Long>("hall_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.organisation_id_seq</code>
	 */
	public static final Sequence<Long> ORGANISATION_ID_SEQ = new SequenceImpl<Long>("organisation_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.personal_id_seq</code>
	 */
	public static final Sequence<Long> PERSONAL_ID_SEQ = new SequenceImpl<Long>("personal_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.position_id_seq</code>
	 */
	public static final Sequence<Long> POSITION_ID_SEQ = new SequenceImpl<Long>("position_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.reservation_id_seq</code>
	 */
	public static final Sequence<Long> RESERVATION_ID_SEQ = new SequenceImpl<Long>("reservation_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.status_id_seq</code>
	 */
	public static final Sequence<Long> STATUS_ID_SEQ = new SequenceImpl<Long>("status_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.structure_id_seq</code>
	 */
	public static final Sequence<Long> STRUCTURE_ID_SEQ = new SequenceImpl<Long>("structure_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.user_id_seq</code>
	 */
	public static final Sequence<Long> USER_ID_SEQ = new SequenceImpl<Long>("user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
