/**
 * This class is generated by jOOQ
 */
package ge.economy.intranet.database.database;


import ge.economy.intranet.database.database.tables.Group;
import ge.economy.intranet.database.database.tables.Hall;
import ge.economy.intranet.database.database.tables.Organisation;
import ge.economy.intranet.database.database.tables.Personal;
import ge.economy.intranet.database.database.tables.Position;
import ge.economy.intranet.database.database.tables.Reservation;
import ge.economy.intranet.database.database.tables.Status;
import ge.economy.intranet.database.database.tables.Structure;
import ge.economy.intranet.database.database.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.group
	 */
	public static final Group GROUP = ge.economy.intranet.database.database.tables.Group.GROUP;

	/**
	 * The table public.hall
	 */
	public static final Hall HALL = ge.economy.intranet.database.database.tables.Hall.HALL;

	/**
	 * The table public.organisation
	 */
	public static final Organisation ORGANISATION = ge.economy.intranet.database.database.tables.Organisation.ORGANISATION;

	/**
	 * The table public.personal
	 */
	public static final Personal PERSONAL = ge.economy.intranet.database.database.tables.Personal.PERSONAL;

	/**
	 * The table public.position
	 */
	public static final Position POSITION = ge.economy.intranet.database.database.tables.Position.POSITION;

	/**
	 * The table public.reservation
	 */
	public static final Reservation RESERVATION = ge.economy.intranet.database.database.tables.Reservation.RESERVATION;

	/**
	 * The table public.status
	 */
	public static final Status STATUS = ge.economy.intranet.database.database.tables.Status.STATUS;

	/**
	 * The table public.structure
	 */
	public static final Structure STRUCTURE = ge.economy.intranet.database.database.tables.Structure.STRUCTURE;

	/**
	 * The table public.user
	 */
	public static final User USER = ge.economy.intranet.database.database.tables.User.USER;
}
